
# https://github.com/marketplace/actions/action-camo-purge

name: Purge image cache

on: workflow_dispatch
  # workflow_dispatch:
  #   inputs:
  #     dummy:
  #       description: 'Dummy input to allow for multiple triggers with variables'
  # schedule:
  #   - cron: '52 2 * * *'  # once per day in the early hours

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
    - uses: kevincobain2000/action-camo-purge@v1
