
# https://pytest-with-eric.com/integrations/pytest-github-actions/
# https://github.com/mamba-org/setup-micromamba

name: Run Unit Tests

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-file: environment.yml
          create-args: pytest pytest-cov
          init-shell: bash powershell
          cache-environment: true
          post-cleanup: all
        
      - name: Install pdemtools
        shell: micromamba-shell {0}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade setuptools 
          cd $GITHUB_WORKSPACE
          pip install .


      - name: Test with pytest
        shell: micromamba-shell {0}
        run: |
            coverage run -m pytest  -v -s  
        

      - name: Generate pytest coverage report
        shell: micromamba-shell {0}
        run: |
            coverage report -m
        
